// Mock user profiles for testing the swipe functionality
export const mockProfiles = [
  {
    user_id: 'mock-1',
    display_name: 'Alex',
    pronouns: 'they/them',
    bio: 'Love reading sci-fi novels and playing board games. Always up for a deep conversation about space exploration or the latest Marvel movie!',
    photos: ['https://randomuser.me/api/portraits/lego/1.jpg'],
    interests: [
      '📚 Reading & Books',
      '🎮 Gaming',
      '🎬 Movies & TV',
      '🔬 Science',
      '🎲 Board Games & Puzzles',
    ],
    match_score: 85,
    distance_km: 3.2,
  },
  {
    user_id: 'mock-2',
    display_name: 'Sam',
    pronouns: 'she/her',
    bio: 'Artist and nature lover. I paint landscapes and enjoy long walks in the forest. Looking for someone to share creative projects with!',
    photos: ['https://randomuser.me/api/portraits/lego/2.jpg'],
    interests: [
      '🎨 Art & Creativity',
      '🌱 Nature & Outdoors',
      '📸 Photography',
      '🧘 Mindfulness & Wellness',
      '✍️ Writing',
    ],
    match_score: 78,
    distance_km: 5.7,
  },
  {
    user_id: 'mock-3',
    display_name: 'Jordan',
    pronouns: 'he/him',
    bio: 'Software developer by day, musician by night. Play guitar in a local band and love attending live music shows. Coffee enthusiast ☕',
    photos: ['https://randomuser.me/api/portraits/lego/3.jpg'],
    interests: [
      '🎵 Music',
      '💻 Technology',
      '🍳 Cooking & Food',
      '🎭 Theater & Performance',
      '📚 Reading & Books',
    ],
    match_score: 92,
    distance_km: 2.1,
  },
  {
    user_id: 'mock-4',
    display_name: 'Riley',
    pronouns: 'they/them',
    bio: 'Fitness trainer and outdoor adventure seeker. When I\'m not at the gym, you\'ll find me hiking or rock climbing. Let\'s stay active together!',
    photos: ['https://randomuser.me/api/portraits/lego/4.jpg'],
    interests: [
      '🏃 Fitness & Sports',
      '🌱 Nature & Outdoors',
      '🧘 Mindfulness & Wellness',
      '📸 Photography',
      '✈️ Travel',
    ],
    match_score: 65,
    distance_km: 8.4,
  },
  {
    user_id: 'mock-5',
    display_name: 'Casey',
    pronouns: 'she/her',
    bio: 'Animal rescue volunteer and plant parent to 20+ houseplants. Passionate about sustainability and making the world a better place.',
    photos: ['https://randomuser.me/api/portraits/lego/5.jpg'],
    interests: [
      '🐾 Animals & Pets',
      '🌱 Nature & Outdoors',
      '🌍 Social Justice',
      '🍳 Cooking & Food',
      '📚 Reading & Books',
    ],
    match_score: 88,
    distance_km: 4.3,
  },
  {
    user_id: 'mock-6',
    display_name: 'Morgan',
    pronouns: 'he/him',
    bio: 'History teacher and trivia night champion. Love learning new things and sharing random facts. Board game nights are my favorite!',
    photos: ['https://randomuser.me/api/portraits/lego/6.jpg'],
    interests: [
      '🎓 Learning & Education',
      '🎲 Board Games & Puzzles',
      '📚 Reading & Books',
      '🎬 Movies & TV',
      '✈️ Travel',
    ],
    match_score: 76,
    distance_km: 6.8,
  },
  {
    user_id: 'mock-7',
    display_name: 'Taylor',
    pronouns: 'they/them',
    bio: 'Graphic designer with a love for minimalist aesthetics. Spend weekends exploring coffee shops and working on personal projects.',
    photos: ['https://randomuser.me/api/portraits/lego/7.jpg'],
    interests: [
      '🎨 Art & Creativity',
      '💻 Technology',
      '📸 Photography',
      '🍳 Cooking & Food',
      '🎨 Crafts & DIY',
    ],
    match_score: 81,
    distance_km: 3.9,
  },
  {
    user_id: 'mock-8',
    display_name: 'Avery',
    pronouns: 'she/her',
    bio: 'Theater kid at heart! Love performing, watching plays, and discussing character development. Always down for karaoke!',
    photos: ['https://randomuser.me/api/portraits/lego/8.jpg'],
    interests: [
      '🎭 Theater & Performance',
      '🎵 Music',
      '🎬 Movies & TV',
      '✍️ Writing',
      '📚 Reading & Books',
    ],
    match_score: 70,
    distance_km: 7.2,
  },
];
